CREATE TABLE deletions(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    update_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    comment VARCHAR(255) NOT NULL
);

CREATE TABLE items(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    deletion_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    name VARCHAR(64) NOT NULL UNIQUE,
    count INT UNSIGNED NOT NULL DEFAULT 0,
    FOREIGN KEY (deletion_id) REFERENCES deletions (id) ON DELETE SET NULL
);
