DROP TRIGGER items_count_too_low_update;
DROP TRIGGER items_count_too_low_insert;

DROP TRIGGER shipment_items_count_too_high_update;
DROP TRIGGER shipment_items_count_too_high_insert;

DROP PROCEDURE check_shipment_items_count;
